---
version: "3.9"

services:
  xui:
    image: d3vilh/x-ui:latest
    container_name: xray-x-ui
    hostname: xray-cloud
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped
